### ISSUE TITLE
Default to cpp instead of c

### ISSUE THREAD

**Issue by Pouja** [kodLite/cppStartingKit#16]
Is it normal behavior that it parses all my c/c++ project files (h, c, cxx, cpp, hh etc.) as C?
If so, is it possible to change that behavior?

**Comment by kodLite** [comment]
Try [this trick](http://cppstartingkitproject-guide.readthedocs.org/en/latest/C++_Starting_Kit_Plugin--Installation--Post--Package_conflict.html) and tell me if it solves your issue.

Thank you for your support.

**Comment by Pouja** [comment]
After following your link and reading the other page, this one did the [trick](http://cppstartingkitproject-guide.readthedocs.org/en/latest/C++_Starting_Kit_Plugin--Installation--Post--Default_Syntax.html), thanks :).

PS: Thank you for building such awesome sublime extension!
