### ISSUE TITLE
Syntax Highlighting name clashing

### ISSUE THREAD

**Issue by Chnossos** [kodLite/cppStartingKit#8]
Since the name of the syntaxes are now the same as the built-in languages (see screenshot), the built-in syntax takes precedence over the Starting Kit when opening a file.

![both_are_enabled](https://cloud.githubusercontent.com/assets/7984363/4755856/d445cca6-5ac8-11e4-9980-4b3fe721a04e.jpg)

(Windows 8.1, ST3 build 3065)

Disabling the C and C++ built-in packages can fix this issue.

**Comment by cipri-tom** [comment]
@Chnossos may you live forever! :grin:
